version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      actions:
        applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    groups:
      php-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      php-security:
        applies-to: security-updates
        patterns: ["*"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
